### ISSUE TITLE
Will it work for MSI GL62M 7RDX?

### ISSUE THREAD

**Issue by ForceGT** [jbwharris/hackintosh-msi-GL72M-7RDX#10] opened 2020-08-20 16:37 UTC
Really want to get it working on this model

**Comment by jbwharris** [comment] 2020-08-20 16:48
Can't see why not. I know there was someone else who was asking on my build who had one.

**Comment by sxzz** [comment] 2020-08-20 16:53
I tried the model `MSI GL62M 7RD 222CN`. Except for the mouse pad, others can work normally. Normal movement and clicking are fine, but don't touch with two fingers.

**Comment by ForceGT** [comment] 2020-08-20 16:55
> I tried the model `MSI GL62M 7RD 222CN`. There is also a problem with my mouse pad. Normal movement and touching are fine, but do not touch with two fingers.

Yeah it hangs suddenly,right?

**Comment by rlindsberg** [comment] 2020-08-20 16:56
https://github.com/rlindsberg/OS-X-on-MSI-GL62m-7REX
In my version, the touchpad works very well. Two finger multitouch works also.

**Comment by jbwharris** [comment] 2020-08-20 17:53
I do feel like something has gone screwy with the touchpad in more recent versions of macOS. My touchpad does work, but the buttons stopped working for right and left click. I had to change it so a click would be registered on tap instead. It hasn't been a huge issue for me since I mostly use my laptop as part of a desktop setup with external mouse and keyboard. I haven't been able to figure if it's a kext or maybe an OpenCore issue or not.

**Comment by ForceGT** [comment] 2020-08-23 19:45
Finally sought some courage and time to do this thing
1st I tried using a partition on an NVME drive where Windows and Arch were present already
So After the long install phase, I rebooted but it seems to come back to the Open Core menu which has two options 
1. Install Mac OS (external)
2. Clean NVRAM

2nd
I formatted my NVME completely, then I created a MacOS journaled partition (as Mac would like it) and GUID Partition Table and reinstalled by creating a 150GB partition of APFS type
Yet the same result 

Where Am I going wrong?
Configs are all taken from your work

**Comment by jbwharris** [comment] 2020-08-23 20:30
I think the trick is to fully pull that Windows drive out when you do the install, then you can be sure you're booting OpenCore. In that previous link I shared there was instructions for adding a boot entry in Windows, as sometimes it loses where the OC EFI is. Then you're able to choose it in the BIOS.

**Comment by ForceGT** [comment] 2020-08-24 04:44
I have no OS on my disk or any other disk
The first one I'm tryna put is MacOS

**Comment by jbwharris** [comment] 2020-08-24 13:12
I ran into the issue of the drive not showing up in the OpenCore list. I'm not sure what I did to fix it, I think it was just one of those things that got solved by following the OpenCore guide thoroughly.

**Comment by ForceGT** [comment] 2020-08-24 13:15
Just sitting in front of my pc from the last 4 days or so, and I tried your config which boots up 110% but then comes back to the install thingy
Now I tried by making my own config but it ends in a kernel panic
I don't know how to proceed further

**Comment by jbwharris** [comment] 2020-08-24 13:41
Maybe try the [OpenCore Sanity Checker](https://opencore.slowgeek.com/), see if there's anything glaring about your setup that you might have missed.

**Comment by ForceGT** [comment] 2020-09-02 13:10
- Any updates on Big Sur or are you planning on upgrading clover,
I booted fine with High Sierra and Clover
But Catalina and OpenCore get stuck at the last moment with a kernel panic
Forums suggest to update stuff

**Comment by jbwharris** [comment] 2020-09-03 01:28
I do have an update to 0.6.0, but there are some bugs with it, so I haven't wanted to really push it. Wanted to have a go at maybe doing a fresh install of Catalina or Big Sur. I think I upgraded to Catalina from Mojave instead of doing a fresh install, so I'm wondering if I've carried through some issues that might be solved starting over.

**Comment by ForceGT** [comment] 2020-09-28 12:04
Finally after so many days got it working 
Now I'm on 10.15.7 
I have only one issue now that the battery drain is huge 
I'll post my efi folder soon

**Comment by rlindsberg** [comment] 2020-09-28 21:30
@ForceGT @jbwharris 
I am working on Catalina with OpenCore and got some errors before the macOS verbose logs

![IMG_0005](https://user-images.githubusercontent.com/2918707/94182290-109aed80-fea1-11ea-8ae0-854a0944c173.PNG)

Do you have any ideas about the error?

**Comment by jbwharris** [comment] 2020-09-28 22:42
I think I have the same thing, it flashes to some white on black text, then flashes and does the verbose boot. I haven't troubleshot that yet. I also have stuff that pops up over the MSI logo.  I really should work through those.

**Comment by abhishektomar-unitedlayer** [comment] 2020-09-29 10:20
Didi you find the solution ?

**Comment by ForceGT** [comment] 2020-09-29 10:27
> I think I have the same thing, it flashes to some white on black text, then flashes and does the verbose boot. I haven't troubleshot that yet. I also have stuff that pops up over the MSI logo. I really should work through those.

The stuff over the MSI logo is usually when you haven't updated the OpenCore version to the latest one

And you should not bother about the other ones @rlindsberg unless everything works fine

**Comment by ForceGT** [comment] 2020-09-29 10:28
> Didi you find the solution ?

Solution to what ? 
Working on MSI GL 62M or the Catalina verbose logs

**Comment by ForceGT** [comment] 2020-09-29 10:30
> Finally after so many days got it working
> Now I'm on 10.15.7
> I have only one issue now that the battery drain is huge
> I'll post my efi folder soon

@jbwharris it would be really helpful if you could tell me if there's a way to optimise the CPU
My Main usage is Android Studio with Chrome and IOS Simulator
It drains battery like anything
That's actually okay
But the ideal drain is also bad
I don't know how to give a quantitative measure though

**Comment by rlindsberg** [comment] 2020-09-29 12:06
> > I think I have the same thing, it flashes to some white on black text, then flashes and does the verbose boot. I haven't troubleshot that yet. I also have stuff that pops up over the MSI logo. I really should work through those.
> 
> The stuff over the MSI logo is usually when you haven't updated the OpenCore version to the latest one
> 
> And you should not bother about the other ones @rlindsberg unless everything works fine

Ok! But I still think error messages could cause some stability issues in macOS, who knows!

**Comment by rlindsberg** [comment] 2020-09-29 12:06
> > Finally after so many days got it working
> > Now I'm on 10.15.7
> > I have only one issue now that the battery drain is huge
> > I'll post my efi folder soon
> 
> @jbwharris it would be really helpful if you could tell me if there's a way to optimise the CPU
> My Main usage is Android Studio with Chrome and IOS Simulator
> It drains battery like anything
> That's actually okay
> But the ideal drain is also bad
> I don't know how to give a quantitative measure though

Can you use Intel Power Gadget to measure CPU power wattage and post a screenshot here?

**Comment by jbwharris** [comment] 2020-09-29 13:03
I installed this recently, but haven't had a chance to go through any of the performance tweaking. I found in seeing other people's builds they usually had lower power consumption, but I wasn't sure if this was an apples to apples comparison since my laptop is a 17". I'd be interested in seeing what others have for their read outs. Mine typically bounces between 3 and 9 watts. 

![image](https://user-images.githubusercontent.com/2962327/94561272-c82d5800-0231-11eb-8f39-50d6af826e8e.png)

Here's the state of my battery 2 years on. It's usually plugged in all the time in my office these days working from home. It was also a floor model in the store, so we may be looking at 2.5-3 years at this point. 

![image](https://user-images.githubusercontent.com/2962327/94561413-f1e67f00-0231-11eb-97bd-35fe7af1bcd9.png)

**Comment by rlindsberg** [comment] 2020-09-29 15:13
I have a lot of Safari tabs open and many RAM hungry apps open, still CPU is very chill.

![Screen Shot 2020-09-29 at 5 06 51 PM](https://user-images.githubusercontent.com/2918707/94576973-46135280-0276-11eb-9899-7c046d1c82a0.png)

This screenshot is from before, when I had battery issue. I was on the first release of 10.14.6 and after reboot, the CPU runs chill and power consumption was good, like the screenshot above. But after a few hours the CPU frequencies started to jump up and down. We can see a lot of spikes in Power-PKG, and video playback is not as smooth as newly rebooted. But a simple reboot will make this problem go away.

However, I haven't think about this problem for a year, because I use the laptop to study and I want to build a functional Hackintosh and just use it for productivity. Thus, I don't know when this problem went away, because now I can have the laptop powered on for days and everything runs just fine.

![bad2](https://user-images.githubusercontent.com/2918707/94577108-7529c400-0276-11eb-8329-817626957452.png)

**Comment by jbwharris** [comment] 2020-09-29 17:37
@rlindsberg  so that's what it could look like then. I'll definitely investigate, since it was never something I was too bothered with before not knowing if that was good/bad performance for my machine.

**Comment by rlindsberg** [comment] 2020-10-01 09:30
About this error:

![IMG_0005](https://user-images.githubusercontent.com/2918707/94182290-109aed80-fea1-11ea-8ae0-854a0944c173.PNG)


I just found out that the problem was on macOS and OpenCore. Here is what I tested:

macOS 10.15.3 + OpenCore 0.5.7 = No errors
macOS 10.15.4 + OpenCore 0.5.7 = Errors

macOS 10.15.3 + OpenCore 0.6.1 = Errors

**Comment by jbwharris** [comment] 2020-10-01 11:11
Are you sticking at 10.15.3 because of the external monitor issue? I actually rolled back because I was always having to unplug the HDMI to get the external monitor to show up after Apple introduced a bug in 10.15.4.

**Comment by rlindsberg** [comment] 2020-10-01 17:58
> Are you sticking at 10.15.3 because of the external monitor issue? I actually rolled back because I was always having to unplug the HDMI to get the external monitor to show up after Apple introduced a bug in 10.15.4.

I have used Mojave until now and I want to update to 10.15.6. But now it seems like I have to stick to 10.15.3 due to the error message.. I patched the frame buffer and can use two external displays. I haven't encountered any issue with the HDMI bug. How can one reproduce it?

**Comment by jbwharris** [comment] 2020-10-01 18:25
My issue post-10.15.4 is

**Comment by rlindsberg** [comment] 2020-10-01 18:55
> My issue post-10.15.4 is this, from my OpenCore readme
> 
> Apple seems to have messed something up with 10.15.4. When the machine boots, it will only show on my external monitor and not the laptop screen. I need it to sleep, then wake it up and the screen will show up on the laptop screen, but not the the external screen. Then to fix this I need to unplug and plug in the HDMI cable and everything will be fine. It's not just a Hackintosh thing, it happens with real Macs too. I've tried the couple troubleshooting options and haven't had any luck with a solution.
> 
> https://www.reddit.com/r/hackintosh/comments/g4nikv/cant_wake_after_sleep_opencore_catalina/
> https://apple.stackexchange.com/questions/381911/16-macbook-pro-doesnt-wake-up-screen-on-lg-5k-external-monitor

Sounds like Apple is following Microsoft: creating more bug than they resolve.
What if you boot up the laptop with the HDMI cable unplugged, and then after you log in, plug the cable?

**Comment by jbwharris** [comment] 2020-10-01 19:11
I unfortunately blew out my 10.15.6 install when I reverted back, so I don't have a ready to test install right now. I think I tried that, but can't recall for sure.

**Comment by ForceGT** [comment] 2020-11-17 10:45
HDMI seems to work perfectly on 10.5.7 
Now asking if anyone updated to Big Sur without any issues

**Comment by jbwharris** [comment] 2020-11-17 17:14
That's good to know. I've been hanging out at 10.15.3 for awhile now wondering if that'd been fixed. Haven't had a crack at Big Sur yet. I just tried OC 0.6.3 this week and it was giving me some grief.

**Comment by jbwharris** [comment] 2020-11-19 17:00
I just upgraded to 10.15.7 and it does indeed fix the HDMI wake problem. But it introduced the 1050 graphics to switching on again, which causes a screen flicker on my laptop. I forget what I needed to do to make it stay off. Guess I'll have to figure that out.

**Comment by ForceGT** [comment] 2021-01-18 06:20
@jbwharris Hey James how do you figure out whether the dGPU has turned on
I think there is a massive battery drain in my laptop ( I am guessing this is the reason) (Loss is almost 1% / 1 min)

Also any luck with Big Sur 
I thought I should try it out today

**Comment by ForceGT** [comment] 2021-01-19 06:46
Updated to Big Sur successfully everything works except AppStore updates stick around too often and everything is a little slower

**Comment by jbwharris** [comment] 2021-01-19 21:22
I have a Big Sur install, but haven't been able to get it to boot. I had this issue where it would take forever for the installer to go to next steps, but I think it is installed, I just can't get it to boot. I'll have to take a poke at your setup and see if there's something I missed.

I did a fresh rebuild with OC 0.6.5 and found it to help with my HDMI wake issues in 10.15.7.  After a decent spell of instability, I'm kinda content with keeping this and plugging away on the new Big Sur instance when I get a chance.

**Comment by jbwharris** [comment] 2021-01-24 23:40
I was able to get Big Sur running with 0.6.5 this weekend. It's working pretty well and I just pushed over a new repo update. Closing ticket.

**Closed by jbwharris** 2021-01-24 23:40 UTC
